// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiAHpsXC4QrQzz1oYpLJr3LNs9wv0VlbY',
    appId: '1:1086653522962:web:aab8d29495f214b78324cb',
    messagingSenderId: '1086653522962',
    projectId: 'city-guide-8b019',
    authDomain: 'city-guide-8b019.firebaseapp.com',
    storageBucket: 'city-guide-8b019.firebasestorage.app',
    measurementId: 'G-9W39G7KJBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMJYxkIwDjBbwLJ71XQ5UzqXEANbuo0CY',
    appId: '1:1086653522962:android:9daecf31c24996298324cb',
    messagingSenderId: '1086653522962',
    projectId: 'city-guide-8b019',
    storageBucket: 'city-guide-8b019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoAsnr1t_8fOE_0cqJDnD2GYYQsBL-FJs',
    appId: '1:1086653522962:ios:ba742c7fa3ee3c0e8324cb',
    messagingSenderId: '1086653522962',
    projectId: 'city-guide-8b019',
    storageBucket: 'city-guide-8b019.firebasestorage.app',
    iosBundleId: 'com.example.citiguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoAsnr1t_8fOE_0cqJDnD2GYYQsBL-FJs',
    appId: '1:1086653522962:ios:ba742c7fa3ee3c0e8324cb',
    messagingSenderId: '1086653522962',
    projectId: 'city-guide-8b019',
    storageBucket: 'city-guide-8b019.firebasestorage.app',
    iosBundleId: 'com.example.citiguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiAHpsXC4QrQzz1oYpLJr3LNs9wv0VlbY',
    appId: '1:1086653522962:web:763db93581612caa8324cb',
    messagingSenderId: '1086653522962',
    projectId: 'city-guide-8b019',
    authDomain: 'city-guide-8b019.firebaseapp.com',
    storageBucket: 'city-guide-8b019.firebasestorage.app',
    measurementId: 'G-86GM0H5C5K',
  );
}
